name: "mixin-checkin"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2023-09-16"
machine_id: 1

log:
  level: "1"
  filename: "checkin.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: true

mongo:
  host: 127.0.0.1
  db: mixin-checkin
  port: 27017

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100
